const KEY='studentPortalState';
const defaults={student:{name:'Alex Rivera',id:'#ST-2024-892',program:'Computer Science',semester:4},gpa:3.88,attendance:{attended:114,total:120},credits:68,totalCredits:120,tasks:[{course:'CS304 · DATABASE SYSTEMS',title:'Database Project Submission',detail:'Schema normalization & indexed SQL queries',due:'Due Tomorrow',urgent:true,done:false},{course:'CS201 · SYSTEMS',title:'Operating Systems Midterm',detail:'Auditorium B • 09:00 AM • Closed Book',due:'In 3 Days',urgent:false,done:false}],schedule:{Thu:[{code:'CS302',name:'Data Structures & Algorithms',time:'10:30 AM – 12:00 PM',room:'Hall 4B',teacher:'Dr. Elena Vance',status:'upcoming'}]}};
let state=load();
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function pct(a,b){return Math.round(a/b*1000)/10}
function render(){document.getElementById('greeting').textContent=`Good morning, ${state.student.name}`;document.getElementById('studentMeta').textContent=`ID: ${state.student.id} · Semester ${state.student.semester} · ${state.student.program}`;document.getElementById('avatar').textContent=initials(state.student.name);document.getElementById('gpa').textContent=state.gpa.toFixed(2);document.getElementById('attendance').textContent=pct(state.attendance.attended,state.attendance.total)+'%';document.getElementById('attendanceSessions').textContent=`${state.attendance.attended} of ${state.attendance.total} sessions`;document.getElementById('attendanceBar').style.width=pct(state.attendance.attended,state.attendance.total)+'%';document.getElementById('credits').textContent=state.credits;document.getElementById('degreePercent').textContent=pct(state.credits,state.totalCredits)+'% Complete';document.getElementById('degreeBar').style.width=pct(state.credits,state.totalCredits)+'%';document.getElementById('taskCount').textContent=state.tasks.filter(t=>!t.done).length;document.getElementById('tasks').innerHTML=state.tasks.slice(0,2).map((t,i)=>`<article class="card task ${t.done?'done':''}"><div class="task-icon"><span class="material-symbols-outlined">${t.urgent?'assignment_late':'event'}</span></div><div class="task-body"><small>${t.course}</small><strong>${t.title}</strong><p>${t.detail}</p></div><div class="due ${t.urgent?'urgent':''}">${t.due}</div><button class="task-check" onclick="toggleTask(${i})"><span class="material-symbols-outlined">${t.done?'check_circle':'radio_button_unchecked'}</span></button></article>`).join('')}
function toggleTask(i){state.tasks[i].done=!state.tasks[i].done;save();toast(state.tasks[i].done?'Task completed':'Task reopened');render()}
function checkIn(code){state.attendance.attended=Math.min(state.attendance.total,state.attendance.attended+1);if(state.schedule.Thu)state.schedule.Thu.forEach(x=>{if(x.code===code)x.status='attended'});save();toast(code+' attendance marked');render()}
function openTasks(){openModal('All Tasks',`<div class="task-list">${state.tasks.map((t,i)=>`<article class="card task"><div class="task-icon"><span class="material-symbols-outlined">assignment</span></div><div class="task-body"><small>${t.course}</small><strong>${t.title}</strong><p>${t.detail}</p></div><button class="btn ghost" onclick="toggleTask(${i});closeModal()">${t.done?'Reopen':'Complete'}</button></article>`).join('')}</div>`)}
function openLeave(){openModal('Request Leave',`<div class="form-grid"><label>Date<input type="date" id="leaveDate"></label><label>Reason<textarea id="leaveReason" rows="4" placeholder="Enter reason"></textarea></label><button class="btn primary" onclick="submitLeave()">Submit Request</button></div>`)}
function submitLeave(){closeModal();toast('Leave request submitted for review')}
function openFee(){openModal('Fee Statement',`<div class="summary-row"><div class="mini"><strong>₹12,500</strong><span>Semester fee</span></div><div class="mini"><strong>₹10,000</strong><span>Transport fee</span></div></div><button class="btn primary full" onclick="closeModal();toast('Statement downloaded')">Download Statement</button>`)}
function showNotifications(){openModal('Notifications',`<div class="notification"><b>Database Project Submission</b><p>Due tomorrow</p></div><div class="notification"><b>Operating Systems Midterm</b><p>Scheduled in 3 days</p></div>`)}
function openSettings(){openModal('Settings',`<button class="btn secondary full" onclick="toggleDark();closeModal()"><span class="material-symbols-outlined">dark_mode</span>Toggle dark mode</button><button class="btn ghost full" onclick="resetData()"><span class="material-symbols-outlined">restart_alt</span>Reset demo data</button>`)}
function resetData(){localStorage.removeItem(KEY);state=structuredClone(defaults);save();closeModal();toast('Demo data reset');render()}
function openModal(title,body){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=body;document.getElementById('modal').classList.add('open')}
function closeModal(){document.getElementById('modal').classList.remove('open')}
function toggleDark(){document.documentElement.classList.toggle('dark');localStorage.setItem('studentPortalDark',document.documentElement.classList.contains('dark'))}
function toggleMenu(){document.querySelector('.sidebar').classList.toggle('show')}
function toast(msg){const e=document.getElementById('toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function initials(n){return n.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});if(localStorage.getItem('studentPortalDark')==='true')document.documentElement.classList.add('dark');render();